.changeset/wet-papayas-battle.md, assistants/naming-conventions/README.md, assistants/naming-conventions/package.json, assistants/reuse-suggestions/README.md, assistants/reuse-suggestions/package.json, assistants/tidy/README.md, assistants/tidy/package.json
=> feat: assistant icons

assistants/naming-conventions/README.md, assistants/reuse-suggestions/README.md, assistants/tidy/README.md
=> feat: pin assistant install links to 5.0.0-next.10

assistants/core/src/rules/groups-max-layers/README.md
=> fix: groups-max-layers readme

.changeset/lazy-monkeys-remain.md, assistants/core/src/rules/layers-no-loose/index.ts
Resolves https://github.com/sketch-hq/Sketch/issues/29969
=> fix: report layers not pages in layers-no-loose

.changeset/chatty-llamas-lick.md, assistants/core/src/locale/en/messages.po, assistants/core/src/locale/zh-Hans/messages.po, assistants/core/src/rules/text-styles-prefer-shared/index.ts
Resolves https://github.com/sketch-hq/Sketch/issues/29643
=> fix: rule title copy

.changeset/gorgeous-days-flow.md, packages/utils/src/process/index.ts
Refs https://github.com/sketch-hq/Sketch/issues/30262
=> feat: do not throw errors for unknown _class values

.changeset/smooth-papayas-look.md, packages/cli/src/index.ts, packages/types/src/types.ts, packages/utils/src/run/run-multiple-assistants/index.ts
Refs https://github.com/sketch-hq/Sketch/issues/29673
=> feat: make RunOutput shape more consistent

.changeset/little-goats-begin.md, packages/types/src/types.ts, packages/utils/src/run/ignore/index.ts, packages/utils/src/run/run-assistant/__tests__/index.ts
=> feat: allow allObjects and objects to be set at same time

.changeset/smooth-islands-reflect.md, packages/utils/src/run/run-assistant/index.ts
=> fix: include all rules in result metadata

.changeset/khaki-pens-check.md, packages/utils/src/rule-utils/index.ts, packages/utils/src/run/run-multiple-assistants/__tests__/index.ts
=> feat: raise rule error if ignored object reported

.changeset/pre.json, README.md, assistants/core/package.json, packages/types/README.md, packages/utils/README.md, yarn.lock
=> feat: exit next pre-release

.changeset/pre.json
=> feat: enter rc pre mode

.changeset/mighty-students-greet.md, assistants/core/src/rules/layer-styles-prefer-library/index.ts, packages/types/src/types.ts, packages/utils/src/process/index.ts, packages/utils/src/rule-utils/__tests__/index.ts, packages/utils/src/rule-utils/index.ts, packages/utils/src/run/run-assistant/__tests__/index.ts, packages/utils/src/run/run-multiple-assistants/__tests__/index.ts
=> feat: rename file prop in ProcessedSketchFile

.changeset/eleven-clouds-flow.md, assistants/core/src/rules/layers-no-loose/index.ts
=> fix: add manual ignore check in layers-no-loose

.changeset/giant-geese-clean.md, assistants/core/src/index.ts, assistants/core/src/rules/debug-timeout/README.md, assistants/core/src/rules/debug-timeout/index.ts, assistants/core/src/rules/layers-no-loose/index.ts, assistants/core/src/rules/layers-subpixel-positioning/index.ts, assistants/reuse-suggestions/src/__tests__/index.test.ts, packages/cli/src/index.ts, packages/types/src/types.ts, packages/utils/package.json, packages/utils/src/process/index.ts, packages/utils/src/rule-utils/__tests__/index.ts, packages/utils/src/rule-utils/index.ts, packages/utils/src/run/run-assistant/__tests__/index.ts, packages/utils/src/run/run-assistant/index.ts, packages/utils/src/run/run-multiple-assistants/__tests__/index.ts, packages/utils/src/run/run-multiple-assistants/index.ts, packages/utils/src/test-helpers/index.ts, yarn.lock
=> feat: rule timeouts

.changeset/smooth-rivers-join.md, assistants/naming-conventions/README.md, assistants/naming-conventions/src/index.ts, assistants/reuse-suggestions/README.md, assistants/tidy/README.md
=> feat: improve workding in artboard naming rule title

.changeset/few-owls-notice.md, assistants/core/src/locale/en/messages.po, assistants/core/src/locale/zh-Hans/messages.po, assistants/core/src/rules/groups-max-layers/index.ts
=> feat: improve wording of groups-max-layers

.changeset/lemon-guests-think.md, assistants/naming-conventions/package.json, assistants/reuse-suggestions/package.json, assistants/tidy/package.json
=> feature/140: Add primary categories to our three assistants

yarn.lock
https://github.com/advisories/GHSA-hxcc-f52p-wc94
=> Bump serialize-javascript

yarn.lock
Fix for https://github.com/advisories/GHSA-vh7m-p724-62c2
=> Bump elliptic

.changeset/famous-pens-glow.md, packages/cli/package.json, packages/cli/src/index.ts, packages/types/package.json, packages/utils/package.json, packages/utils/src/files/__tests__/index.ts, packages/utils/src/files/index.ts, packages/utils/src/get-image-metadata/__tests__/index.ts, packages/utils/src/process/__tests__/index.ts, packages/utils/src/rule-utils/__tests__/index.ts, packages/utils/src/run/ignore/__tests__/index.ts, packages/utils/src/run/run-assistant/__tests__/index.ts, packages/utils/src/run/run-multiple-assistants/__tests__/index.ts, packages/utils/src/test-helpers/index.ts, yarn.lock
- Use the new [`@sketch-hq/sketch-file` package](https://www.npmjs.com/package/@sketch-hq/sketch-file)
- Removed `fromFile` unit tests, they have been migrated to the package
- Use latest [`@sketch-hq/sketch-file-format-ts`](https://www.npmjs.com/package/@sketch-hq/sketch-file-format-ts)
- Reorganised imports everywhere
=> Update dependency to use fromFile from `@sketch-hq/sketch-file`

.changeset/slow-buckets-cough.md, packages/utils/src/assistant/__tests__/index.ts, packages/utils/src/assistant/index.ts
=> Change config merge behaviour

.changeset/silly-mayflies-perform.md, packages/types/src/types.ts, packages/utils/src/assistant-config-schema/__tests__/index.ts, packages/utils/src/assistant-config-schema/index.ts
=> Add assistant config schema api

.changeset/blue-countries-shout.md, packages/utils/src/index.ts
Export was previously missing.
=> Export buildAssistantConfigSchema at utils package level
